# Parmaeters for NEA cod
# Jan 2024 update: Mikko's email titled "Questions on NEA Fishery new parameters"
# Apr 2024 update: After discussion with Mikko summarized in onenote doc

## FISH PARAMETERS
## ---------------------
[fish]

beta = 0.693903 # Exponent of energy acquisition,estimated,growth and reproduction
r = 0.084981 # Energetic GSI,estimated,growth and reproduction
c = 5.041398 # Energy acquisition parameter,estimated,growth and reproduction
q = 1 # Energy density of soma compared to gonads,assumed,growth and reproduction
k = 0.00664 # Length-weight coefficient,estimated,growth and reproduction
alpha = 3.060305235 # Length-weight exponent,estimated,growth and reproduction
E1 = 2500 # Number of eggs per unit weight of gonad ,Enberg et al. 2009,growth and reproduction

# Maturation
pmrn_lp50 = 122.647519 # Intercept of the PMRN midpoint curve,,PMRN
pmrn_width = 29.74 # 46.229621 # Width of the PMRN midpoint curve
pmrn_slope = -6.324434 # Slope of the PMRN midpoint curve
pmrn_envelope = 0.25   # Definition of the width
Lref = 70.48712 # 80
# temperature dependence of maturation
# Source: Mikko's email "COMFORT Poster" 10 Jul 2022. Jan 2024 update: No update needed. 
beta3 = 1.374 

# Mortality
; # Pure power law
; Mref = 0.20775 # ##0.1421 #<--old value from file
; b    =  1.58127 ###1.8131
; M0   = 0 #
# Power law + offset
# ---------------------------
# Values in first column are the latest closed-loop calibration
# Values in second column are Mikko's independent calibration
Mref = 0.03239047 # 0.062994 # 
b    = 0.9809538  # 2.455715 # 
M0   = 0.2 # 0.162126 # 

# temperature dependence of mortality
# Source: Literature review provided by Mikko (estimation of cod parameters.docx)
cT = 0.196
Tref = 5.61
# Trait dependence of mortality
alpha4 = 0.0158 # 0.158
alpha1_ref = 5.041398 # Same as c
alpha5 = 1.73 # 0.749 #2
gsi_ref = 0.084981 # Same as r
Mspawning = 0 # Length-independent natural mortality in spawning grounds 

# Recruitment
L0 = 9.1 # Juvenile length (length at age 1) 
s0 = 0.01924969 # Survival probability until recruitment (calibrated at population level)
# Temperature and density dependence of recruitment.
# Source: Mikko's email "COMFORT Poster" 11 Jul 2022. Jan 2024: updated
Bhalf = 498.1003e6 #187837572 #3.65e8  # Bhalf for recruitment 
beta4 = 0.5380 # temperature dependence of recruitment

# Growth: temperature and density dependence of growth
# Source: Model fits provided by Mikko (estimation of cod parameters.docx). Jan 2024: updated 
# log(dL) = l0 + beta1*dB (kiloTons) + beta2*dT (degC)
beta1 = -8.407e-5  
beta2 = 0.18035
Tmean = 5.61
tsbmean = 1.93e3 # i.e. 1.93e9/1e6 # convert kg to kT

# Processes
growth_model_name = Bioenergetic
maturation_model_name = Bioenergetic
mortality_model_name = Empirical
recruitment_model_name = RickerBioenergetic

[stock]

recruitmentAge = 3
sigmaf = 0.4858775   # environmental stochasticity


## POPULATION PARAMETERS
## ---------------------
[population]

recruitmentAge = 3;

# environmental stochasticity
sigmaf = 0.4858775;

# effort dynamics and employment
q = 2.83e-6  	# scaling parameter relating to catchability and density
dsea = 0.01953203 # 0.054  # Required Person-years per vessel day
dmax = 30000e20  # max available person-years
dshr = 5.170907e-06 # 0.000004  # FTE/kg
b = 0.75  	# density dependence

# revenue and profit 
price_sea = 20.21291 # 13.13  	# landing price NOK/kg
price_shore = 30.14407 # 17.0  	# selling price NOK/kg
fee_ratio = 0.03880684  # fees as proportion of landed value

salary_sea = 955804.8 # 1078000  		# employment cost sea NOK/FTE
salary_shore = 519495.5 # 348000  		# employment cost shore NOK/FTE
fixed_costs_sea = 920942110 # 351123000  # fixed costs sea NOK (= average per unit * #units)
fixed_costs_shore = 154510557 # 1032468000  # fixed costs shore NOK
variable_costs_sea = 11489.42 # 65000; 		# variable costs NOK/vessel day
scale_catch = 1 # 0.4768143 # 0.356; #0.53; 		# percentage of total codfish catch that is cod - this is now included in other relevant parameters or data, hence set to 1 in new parameterization

[fishery]

# Fraction of harvest from spawning grounds
F_spf = 0.0 # 0.07  # WGEVO parameterization file
rho = 0.12   # Fraction of control fishing mortaility rate imposed in spawning grounds  
f_spf_before = 0.5 

# management / fishing selectivity
# F = 1/(1+exp(-sf(L-lf50)))
# F = F1/(1+exp(-F2*(L-F3))) - F6/(1+exp(-F4*(L-F5))) 
# When the lmin of the fishery is lmin_sq, 
#   the observed fishing mortality parameters (F1-F6) are as below
#   Thus, lmin_sq doesnt necessarily equal F3. Rather, we shift F3 and F5
#   by the same amount that we shift lmin from lmin_sq
F1 = 0.6901
F2 = 0.06517
F3 = 68.81
F4 = 0.4151
F5 = 112.8
F6 = 0.4381674
lmin = 45

using_empirical_fref = true
Fref_empirical_file = ../data/selection.spline.reduced.csv
