# Fleet 1 parameters

[fleet]

# management / fishing selectivity
# Below are status quo parameters for the fishery
# F = 1/(1+exp(-sf(L-lf50)))
# F = F1/(1+exp(-F2*(L-F3))) - F6/(1+exp(-F4*(L-F5))) 
# When the lmin of the fishery is lmin_sq, 
#   the observed fishing mortality parameters (F1-F6) are as below
#   Thus, lmin_sq doesnt necessarily equal F3. Rather, we shift F3 and F5
#   by the same amount that we shift lmin from lmin_sq
# F1 = 0.6901
# F2 = 0.06517
# F3 = 68.81
# F4 = 0.4151
# F5 = 112.8
# F6 = 0.4381674
# lmin = 45

# effort dynamics and employment
q = 2.83e-6  	# scaling parameter relating to catchability and density
dsea = 0.01953203 # 0.054  # Required Person-years per vessel day
dmax = 30000e20  # max available person-years
dshr = 5.170907e-06 # 0.000004  # FTE/kg
b = 0.75  	# density dependence

# revenue and profit 
price_sea = 20.21291 # 13.13  	# landing price NOK/kg
price_shore = 30.14407 # 17.0  	# selling price NOK/kg
fee_ratio = 0.03880684  # fees as proportion of landed value

salary_sea = 955804.8 # 1078000  		# employment cost sea NOK/FTE
salary_shore = 519495.5 # 348000  		# employment cost shore NOK/FTE
fixed_costs_sea = 920942110 # 351123000  # fixed costs sea NOK (= average per unit * #units)
fixed_costs_shore = 154510557 # 1032468000  # fixed costs shore NOK
variable_costs_sea = 11489.42 # 65000; 		# variable costs NOK/vessel day
scale_catch = 1 # 0.4768143 # 0.356; #0.53; 		# percentage of total codfish catch that is cod - this is now included in other relevant parameters or data, hence set to 1 in new parameterization

quota = 0.5

control_model = exp # exp or linear
max_chi = 100
chi0_scalar_slope = 1.5 
window_dt = 0.1  # // window length [years]
