---
title: "Scan over harvest rate and temperature"
author: "Jaideep"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(fisheRy)

setwd(here::here("vignettes"))
```



```{r setup-fishery}
# define parameter files
params_file_fleet = here::here("params/fleet_1_params.ini")
params_file_spf = here::here("params/fleet_1s_params.ini")
params_file_fish  = here::here("params/cod_params.ini")

# Create a fleet and read parameters
fleet = new(Fleet)
fleet$readParams(params_file_fleet, F)
fleet$par$print()

# Create a prototype fish to construct the population
fish = new(Fish, params_file_fish)
fish$natural_mort_scalar = 1
fish$setMortalityCurveEmpirical(here::here("data/naturalmort.spline.csv"))
fish$par$print()
```

# Fishery Simulation

```{r configure-fishery}
hvec = seq(0.1, 0.99, length.out = 10)
lminvec = c(45)
Tvec = seq(3, 7, length.out=7)
```

```{r}
# Craeate the fishery. Note that we do not need to explicitly create a population - it is contained within the fishery
fishery = new(Fishery, params_file_fish, fish);
fishery$par$print()

fishery$addFleet(params_file_fleet, T);
fishery$addSpawnerFleet(params_file_spf, T);

v = fishery$equilibriateNaturalPopulation(5.61, 2e6, 200);
fishery$set_superFishSize(2e6)

# Initialize the 
fishery$init(1000, 0, 5.61);
v2 = fishery$equilibriateWithoutFishing(5.61, 200)

df = as.data.frame(matrix(data=v2, nrow=200, byrow=T))
df = df |> setNames(c(			
      "ssb", 
			"tsb",
			"maturity",
			"nrecruits",
			"factor_dr",
			"n_superfish"))

df |> 
  slice(-1) |>
  mutate(t = 1:n()) |> 
  pivot_longer(-t) |>
  ggplot(aes(x=t, y=value)) +
  geom_line()+
  facet_wrap(~name, scales="free")

```

# Running and Visualizing Simulation

Simulate the fishery over time and visualize key outputs.

```{r}
colnames=fishery$colnames
```


```{r run-simulation}
v3 = fishery$simulate_multi(Tvec, lminvec, hvec, 200, 0, 1, F)

v3_avg = apply(v3, MARGIN=c(2,3,4,5), FUN=mean)

plots = list()
for (i in 1:4){
  plots[[i]] = v3_avg[,,,i] |> 
    as.data.frame() |> 
    setNames(Tvec) |> 
    mutate(h = hvec) |> 
    pivot_longer(-h, names_to = "T") |> 
    mutate(T = as.numeric(T)) |>
    ggplot(aes(x=h, y=T, fill=value)) +
    geom_raster() +
    scale_fill_viridis_c() + 
    ggtitle(c("SSB", "Yield", "Employment", "Profit")[i])
}

library(patchwork)
(plots[[1]]+plots[[2]])/(plots[[3]]+plots[[4]])

```


### Max avg utils with profit masking

```{r}
utils = standardized_utils(v3, colnames)

plots = list()
for (i in 1:4){
  plots[[i]] = utils$utils_std_tavg[,,,i] |> 
    as.data.frame() |> 
    setNames(Tvec) |> 
    mutate(h = hvec) |> 
    pivot_longer(-h, names_to = "T") |> 
    mutate(T = as.numeric(T)) |>
    ggplot(aes(x=h, y=T, fill=value)) +
    geom_raster() +
    scale_fill_viridis_c() + 
    ggtitle(c("SSB", "Yield", "Employment", "Profit")[i])
}

library(patchwork)
(plots[[1]]+plots[[2]])/(plots[[3]]+plots[[4]])


```


### Stakeholder satisfaction

```{r}
weights =c(  
#   ssb  yiel empl profit
    0.0, 0.3, 0.0, 0.7,	  # industrial
    0.3, 0.5, 0.1, 0.1,	  # artisanal
    0.3, 0.2, 0.5, 0.0,	  # employment-maximizing policymakers
    0.2, 0.2, 0.0, 0.6,	  # profit-maximizing policymakers
    0.5, 0.1, 0.2, 0.2	  # conservationists
)

ss = stakeholder_satisfaction(utils_std=utils$utils_std, weights = weights, profit_mask=utils$profit_mask, utilnames = colnames, nstake=5, nu=4)

plots = list()
for (i in 1:5){
  plots[[i]] = ss[,,,i] |> 
    as.data.frame() |> 
    setNames(Tvec) |> 
    mutate(h = hvec) |> 
    pivot_longer(-h, names_to = "T") |> 
    mutate(T = as.numeric(T)) |>
    ggplot(aes(x=h, y=T, fill=value)) +
    geom_raster() +
    scale_fill_viridis_c() + 
    ggtitle(c("industrial", "artisanal", "employment", "profit", "conservationists")[i])
}

library(patchwork)
(plots[[1]]+plots[[3]])/(plots[[4]]+plots[[5]])

```

