---
title: "Simulating a fish population with fishing"
author: "Jaideep Joshi"
date: "28 March 2022"
output: html_document
editor_options:
  chunk_output_type: inline
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F, echo = F}
library(fisheRy)
library(tidyverse)
source("../tests/ref/parameters.cod.R")
source("../tests/ref/simulator.7.R")
```


```{r}
params_file = "../params/cod_params.ini"
```

```{r }
run_and_plot = function(h, lf){
  nsup = 2e6
  nsteps = 200
  
  fish = new(Fish, params_file)
  
  pop = new(Population, fish)
  pop$readParams(params_file, F)
  pop$set_superFishSize(nsup)
  pop$verbose = T
  pop$init(1000, 5.61)
  pop$noFishingEquilibriate(5.61)
  
  sim = new(Simulator, fish)
  sim$setNaturalPopulation(pop)
  
  res_ibm = sim$simulate(pop, lf, h, nsteps, 1.93e3, 5.61, F, "../fishery_output/out_22_45.csv")
  
  
  p1 = res_ibm %>% 
    mutate(year = 1:n()) %>% 
    select(year, ssb, yield, employment.sea, employment.shore, profit, nrecruits, nfish_ra, Nrel, yield_spf, chi, Fref_ref, Mort_ref) %>% 
    pivot_longer(-year) %>% 
    ggplot(aes(x=year, y=value))+
    geom_line()+
    facet_wrap(~name, scales="free_y")
  
  age_dists = read.csv("../fishery_output/out_22_45.csv")
  
  p2 = age_dists %>% 
    select(age, Year, N, catch_N, mat) %>% 
    mutate(across(-c(age, Year),
                  scale)) %>% 
    pivot_longer(-c(age, Year)) %>% 
    ggplot()+
    geom_raster(aes(x=Year, y=age, fill=value))+
    facet_wrap(~name)+
    scale_fill_viridis_c()
  
  print(p1)
  print(p2)
}
  
```

## Simulate with good lmin

```{r}
run_and_plot(h = 0.22, lf = 45)
```

## Simulate with edge lmin

```{r}
run_and_plot(h = 0.22, lf = 120)
```

## Simulate with bad lmin

```{r}
run_and_plot(h = 0.22, lf = 180)
```
