# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_fished_dry_run_wrapper <- function(stock_ptr, fleets_list, x, y, a, b) {
    .Call(`_fisheRy_get_fished_dry_run_wrapper`, stock_ptr, fleets_list, x, y, a, b)
}

